In [ ]:
!pip install requests

Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests) (2026.2.25)

# Crypto Data (CoinGecko API)

In [ ]:
import requests
#by change the page number from 1 to 4 and save the each 200 response in each data
# for loop condition is not satisfy here due to url
url = f"https://api.coingecko.com/api/v3/coins/markets?vs_currency=inr&per_page=250&order=market_cap_desc&page=1&sparkline=False"
response = requests.get(url)
data1 = response.json()

In [ ]:
url = f"https://api.coingecko.com/api/v3/coins/markets?vs_currency=inr&per_page=250&order=market_cap_desc&page=2&sparkline=False"
response = requests.get(url)
data2 = response.json()

In [ ]:
url = f"https://api.coingecko.com/api/v3/coins/markets?vs_currency=inr&per_page=250&order=market_cap_desc&page=3&sparkline=False"
response = requests.get(url)
data3 = response.json()

In [ ]:
url = f"https://api.coingecko.com/api/v3/coins/markets?vs_currency=inr&per_page=250&order=market_cap_desc&page=4&sparkline=False"
response = requests.get(url)
data4 = response.json()

In [ ]:
# convert the data into dataframe
import pandas as pd
df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)
df3 = pd.DataFrame(data3)
df4 = pd.DataFrame(data4)

In [ ]:
# combine the dataframes
df = pd.concat([df1,df2,df3,df4])
df.head()

,id,symbol,name,image,current_price,market_cap,market_cap_rank,fully_diluted_valuation,total_volume,high_24h,...,max_supply,ath,ath_change_percentage,ath_date,atl,atl_change_percentage,atl_date,roi,last_updated,status
0,bitcoin,btc,Bitcoin,https://coin-images.coingecko.com/coins/images...,6437761.00,1.287169e+14,1.0,1.287169e+14,4.546990e+12,6577840.00,...,2.100000e+07,11187013.00,-42.45326,2025-10-06T18:57:42.558Z,3993.420000,1.611093e+05,2013-07-05T00:00:00.000Z,None,2026-03-11T15:34:01.629Z,NaN
1,ethereum,eth,Ethereum,https://coin-images.coingecko.com/coins/images...,187588.00,2.264029e+13,2.0,2.264029e+13,1.822790e+12,191489.00,...,NaN,431946.00,-56.57129,2025-08-24T19:21:03.333Z,28.130000,6.667331e+05,2015-10-20T00:00:00.000Z,"{'times': 37.96461754823267, 'currency': 'btc'...",2026-03-11T15:34:03.125Z,NaN
2,tether,usdt,Tether,https://coin-images.coingecko.com/coins/images...,92.16,1.694655e+13,3.0,1.745036e+13,6.972884e+12,92.36,...,NaN,105.52,-12.66187,2025-01-25T16:51:57.989Z,36.860000,1.500247e+02,2015-03-02T00:00:00.000Z,None,2026-03-11T15:32:54.028Z,NaN
3,binancecoin,bnb,BNB,https://coin-images.coingecko.com/coins/images...,59253.00,8.083927e+12,4.0,8.083927e+12,7.409620e+10,59977.00,...,2.000000e+08,121422.00,-51.20095,2025-10-13T08:41:24.131Z,2.580000,2.292310e+06,2017-10-19T00:00:00.000Z,None,2026-03-11T15:34:01.294Z,NaN
4,ripple,xrp,XRP,https://coin-images.coingecko.com/coins/images...,127.14,7.796423e+12,5.0,1.273164e+13,2.557726e+11,131.53,...,1.000000e+11,313.99,-59.50743,2025-07-21T15:02:00.541Z,0.159343,7.969107e+04,2013-08-16T00:00:00.000Z,None,2026-03-11T15:33:27.727Z,NaN

In [ ]:
import pandas as pd

# Define the list of columns
selected_columns = [
    'id', 'symbol', 'name', 'current_price', 'market_cap',
    'market_cap_rank', 'total_volume', 'circulating_supply',
    'total_supply', 'ath', 'atl', 'last_updated'
]

#Filter the DataFrame
filtered_df = df[selected_columns].copy()

# convert 'last_updated' to just a Date (removing the time)
filtered_df['date'] = pd.to_datetime(filtered_df['last_updated']).dt.date
filtered_df = filtered_df.drop('last_updated',axis = 1)
# View the result
filtered_df.head()

,id,symbol,name,current_price,market_cap,market_cap_rank,total_volume,circulating_supply,total_supply,ath,atl,date
0,bitcoin,btc,Bitcoin,6437761.00,1.287169e+14,1.0,4.546990e+12,2.000087e+07,2.000087e+07,11187013.00,3993.420000,2026-03-11
1,ethereum,eth,Ethereum,187588.00,2.264029e+13,2.0,1.822790e+12,1.206920e+08,1.206920e+08,431946.00,28.130000,2026-03-11
2,tether,usdt,Tether,92.16,1.694655e+13,3.0,6.972884e+12,1.838901e+11,1.893571e+11,105.52,36.860000,2026-03-11
3,binancecoin,bnb,BNB,59253.00,8.083927e+12,4.0,7.409620e+10,1.363582e+08,1.363582e+08,121422.00,2.580000,2026-03-11
4,ripple,xrp,XRP,127.14,7.796423e+12,5.0,2.557726e+11,6.122783e+10,9.998570e+10,313.99,0.159343,2026-03-11

In [ ]:
filtered_df.to_csv("Cryptocurrencies.csv",index=False)

# TOP 3 COINS

"bitcoin","ethereum","tether",

In [ ]:
coin_id = "bitcoin" # change it to ethereum,tether accordingly
url = f"https://api.coingecko.com/api/v3/coins/{coin_id}/market_chart?vs_currency=usd&days=365"
response = requests.get(url)

bitcoin_data = response.json()

In [ ]:
coin_id = "ethereum" # change it to ethereum,tether accordingly
url = f"https://api.coingecko.com/api/v3/coins/{coin_id}/market_chart?vs_currency=usd&days=365"
response = requests.get(url)

ethereum_data = response.json()

In [ ]:
coin_id = "tether" # change it to ethereum,tether accordingly
url = f"https://api.coingecko.com/api/v3/coins/{coin_id}/market_chart?vs_currency=usd&days=365"
response = requests.get(url)

tether_data = response.json()

In [ ]:
import pandas as pd
bitcoin_df = pd.DataFrame(bitcoin_data)
ethereum_df = pd.DataFrame(ethereum_data)
tether_df = pd.DataFrame(tether_data)

In [ ]:
bitcoin_df['timestamp'] = bitcoin_df['prices'].apply(lambda x: x[0])
bitcoin_df['timestamp'] = pd.to_datetime(bitcoin_df['timestamp'], unit='ms')

bitcoin_df['prices'] = bitcoin_df['prices'].apply(lambda x: x[1])
bitcoin_df['market_caps'] = bitcoin_df['market_caps'].apply(lambda x: x[1])
bitcoin_df['total_volumes'] = bitcoin_df['total_volumes'].apply(lambda x: x[1])

bitcoin_df = bitcoin_df[['timestamp', 'prices', 'market_caps', 'total_volumes']]
bitcoin_df['coin_id'] = 'bitcoin'
bitcoin_df = bitcoin_df.rename(columns={"prices":"prices_usd"})
bitcoin_df.head()

   timestamp    prices_usd   market_caps  total_volumes  coin_id
0 2025-03-12  82799.108029  1.642997e+12   5.640446e+10  bitcoin
1 2025-03-13  83884.245788  1.662503e+12   4.178219e+10  bitcoin
2 2025-03-14  81098.900524  1.608477e+12   3.258359e+10  bitcoin
3 2025-03-15  83971.709161  1.665726e+12   2.857148e+10  bitcoin
4 2025-03-16  84391.690876  1.674173e+12   1.076180e+10  bitcoin

In [ ]:
ethereum_df['timestamp'] = ethereum_df['prices'].apply(lambda x: x[0])
ethereum_df['timestamp'] = pd.to_datetime(ethereum_df['timestamp'], unit='ms')

ethereum_df['prices'] = ethereum_df['prices'].apply(lambda x: x[1])
ethereum_df['market_caps'] = ethereum_df['market_caps'].apply(lambda x: x[1])
ethereum_df['total_volumes'] = ethereum_df['total_volumes'].apply(lambda x: x[1])

ethereum_df = ethereum_df[['timestamp', 'prices', 'market_caps', 'total_volumes']]
ethereum_df['coin_id'] = 'ethereum'
ethereum_df = ethereum_df.rename(columns={"prices":"prices_usd"})
ethereum_df.head()

   timestamp   prices_usd   market_caps  total_volumes   coin_id
0 2025-03-12  1921.309923  2.320249e+11   3.004660e+10  ethereum
1 2025-03-13  1910.655138  2.304437e+11   2.449931e+10  ethereum
2 2025-03-14  1862.794937  2.246589e+11   1.921241e+10  ethereum
3 2025-03-15  1910.666270  2.304769e+11   1.294997e+10  ethereum
4 2025-03-16  1939.785688  2.339703e+11   6.944891e+09  ethereum

In [ ]:
tether_df['timestamp'] = tether_df['prices'].apply(lambda x: x[0])
tether_df['timestamp'] = pd.to_datetime(tether_df['timestamp'], unit='ms')

tether_df['prices'] = tether_df['prices'].apply(lambda x: x[1])
tether_df['market_caps'] = tether_df['market_caps'].apply(lambda x: x[1])
tether_df['total_volumes'] = tether_df['total_volumes'].apply(lambda x: x[1])

tether_df = tether_df[['timestamp', 'prices', 'market_caps', 'total_volumes']]
tether_df['coin_id'] = 'tether'
tether_df = tether_df.rename(columns={"prices":"prices_usd"})
tether_df.head()

   timestamp  prices_usd   market_caps  total_volumes coin_id
0 2025-03-12    0.999731  1.429581e+11   5.853343e+10  tether
1 2025-03-13    0.999743  1.431450e+11   6.800429e+10  tether
2 2025-03-14    0.999535  1.432788e+11   2.648970e+10  tether
3 2025-03-15    1.000009  1.433472e+11   4.911632e+10  tether
4 2025-03-16    1.000019  1.434677e+11   1.539615e+10  tether

In [ ]:
df = pd.concat([bitcoin_df,ethereum_df,tether_df], ignore_index= False)
df['date'] = df['timestamp'].dt.date

In [ ]:
df = df.drop(columns=['total_volumes','market_caps','timestamp'])
df.head()

     prices_usd  coin_id        date
0  82799.108029  bitcoin  2025-03-12
1  83884.245788  bitcoin  2025-03-13
2  81098.900524  bitcoin  2025-03-14
3  83971.709161  bitcoin  2025-03-15
4  84391.690876  bitcoin  2025-03-16

In [ ]:
df.to_csv("Crypto_prices.csv",index=False)

# OIL PRICES

In [ ]:
import pandas as pd
oil_df = pd.read_csv("https://raw.githubusercontent.com/datasets/oil-prices/main/data/wti-daily.csv")
filtered_df = oil_df[oil_df['Date'].between('2020-01-01', '2026-02-28')]
filtered_df.head()

            Date  Price
8569  2020-01-02  61.17
8570  2020-01-03  63.00
8571  2020-01-06  63.27
8572  2020-01-07  62.70
8573  2020-01-08  59.65

In [ ]:
filtered_df.to_csv("Oil_prices.csv",index=False)

# Stock Prices (Yahoo Finance API)

In [ ]:
import yfinance as yf
import pandas as pd

# Choose indices
tickers = ["^GSPC", "^IXIC", "^NSEI"]
start_date = "2020-01-01"
end_date = "2026-02-28"

# Download historical data
stocks_df = yf.download(tickers, start=start_date, end=end_date, group_by="ticker")
stocks_df.head()

/tmp/ipykernel_152/4037827274.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  stocks_df = yf.download(tickers, start=start_date, end=end_date, group_by="ticker")
[*********************100%***********************]  3 of 3 completed

Ticker            ^GSPC                                                       \
Price              Open         High          Low        Close        Volume
Date
2020-01-01          NaN          NaN          NaN          NaN           NaN
2020-01-02  3244.669922  3258.139893  3235.530029  3257.850098  3.459930e+09
2020-01-03  3226.360107  3246.149902  3222.340088  3234.850098  3.484700e+09
2020-01-06  3217.550049  3246.840088  3214.639893  3246.280029  3.702460e+09
2020-01-07  3241.860107  3244.909912  3232.429932  3237.179932  3.435910e+09

Ticker            ^IXIC                                                       \
Price              Open         High          Low        Close        Volume
Date
2020-01-01          NaN          NaN          NaN          NaN           NaN
2020-01-02  9039.459961  9093.429688  9010.889648  9092.190430  2.862700e+09
2020-01-03  8976.429688  9065.759766  8976.429688  9020.769531  2.586520e+09
2020-01-06  8943.500000  9072.410156  8943.500000  9071.469727  2.810450e+09
2020-01-07  9076.639648  9091.929688  9042.549805  9068.580078  2.381740e+09

Ticker             ^NSEI
Price               Open          High           Low         Close    Volume
Date
2020-01-01  12202.150391  12222.200195  12165.299805  12182.500000  304100.0
2020-01-02  12198.549805  12289.900391  12195.250000  12282.200195  407700.0
2020-01-03  12261.099609  12265.599609  12191.349609  12226.650391  428800.0
2020-01-06  12170.599609  12179.099609  11974.200195  11993.049805  396500.0
2020-01-07  12079.099609  12152.150391  12005.349609  12052.950195  447800.0

In [ ]:
stocks_1 = stocks_df['^NSEI'].reset_index()
stocks_1["Ticker"] = "^NSEI"
stocks_1.head()

Price,Date,Open,High,Low,Close,Volume,Ticker
0,2020-01-01,12202.150391,12222.200195,12165.299805,12182.500000,304100.0,^NSEI
1,2020-01-02,12198.549805,12289.900391,12195.250000,12282.200195,407700.0,^NSEI
2,2020-01-03,12261.099609,12265.599609,12191.349609,12226.650391,428800.0,^NSEI
3,2020-01-06,12170.599609,12179.099609,11974.200195,11993.049805,396500.0,^NSEI
4,2020-01-07,12079.099609,12152.150391,12005.349609,12052.950195,447800.0,^NSEI

In [ ]:
stocks_2 = stocks_df['^IXIC'].reset_index()
stocks_2["Ticker"] = "^IXIC"
stocks_2.head()

Price,Date,Open,High,Low,Close,Volume,Ticker
0,2020-01-01,NaN,NaN,NaN,NaN,NaN,^IXIC
1,2020-01-02,9039.459961,9093.429688,9010.889648,9092.190430,2.862700e+09,^IXIC
2,2020-01-03,8976.429688,9065.759766,8976.429688,9020.769531,2.586520e+09,^IXIC
3,2020-01-06,8943.500000,9072.410156,8943.500000,9071.469727,2.810450e+09,^IXIC
4,2020-01-07,9076.639648,9091.929688,9042.549805,9068.580078,2.381740e+09,^IXIC

In [ ]:
stocks_3 = stocks_df['^GSPC'].reset_index()
stocks_3["Ticker"] = "^GSPC"
stocks_3.head()

Price,Date,Open,High,Low,Close,Volume,Ticker
0,2020-01-01,NaN,NaN,NaN,NaN,NaN,^GSPC
1,2020-01-02,3244.669922,3258.139893,3235.530029,3257.850098,3.459930e+09,^GSPC
2,2020-01-03,3226.360107,3246.149902,3222.340088,3234.850098,3.484700e+09,^GSPC
3,2020-01-06,3217.550049,3246.840088,3214.639893,3246.280029,3.702460e+09,^GSPC
4,2020-01-07,3241.860107,3244.909912,3232.429932,3237.179932,3.435910e+09,^GSPC

In [ ]:
stocks_df = pd.concat([stocks_1,stocks_2,stocks_3],ignore_index=True)
stocks_df.head()

Price,Date,Open,High,Low,Close,Volume,Ticker
0,2020-01-01,12202.150391,12222.200195,12165.299805,12182.500000,304100.0,^NSEI
1,2020-01-02,12198.549805,12289.900391,12195.250000,12282.200195,407700.0,^NSEI
2,2020-01-03,12261.099609,12265.599609,12191.349609,12226.650391,428800.0,^NSEI
3,2020-01-06,12170.599609,12179.099609,11974.200195,11993.049805,396500.0,^NSEI
4,2020-01-07,12079.099609,12152.150391,12005.349609,12052.950195,447800.0,^NSEI

In [ ]:
stocks_df.to_csv("Stocks_prices.csv")

In [1]:
import pandas as pd
crpyto_curr = pd.read_csv("/content/drive/MyDrive/datascience/Mini Projects/DS_Cross-Market Analysis/Cryptocurrencies.csv")
crpyto_price = pd.read_csv("/content/drive/MyDrive/datascience/Mini Projects/DS_Cross-Market Analysis/Crypto_prices.csv")
oil_price = pd.read_csv("/content/drive/MyDrive/datascience/Mini Projects/DS_Cross-Market Analysis/Oil_prices.csv")
stocks_price = pd.read_csv("/content/drive/MyDrive/datascience/Mini Projects/DS_Cross-Market Analysis/Stocks_prices.csv")

# SQL DATABASE

In [2]:
import sqlite3
import pandas as pd

# Connect to one database file (usually better than 4 separate files)
conn = sqlite3.connect("Cross_Market_Analysis")
cursor = conn.cursor()

# Define specific schemas for your 4 tables
tables = {
    "Cryptocurrencies": "id VARCHAR(50) PRIMARY KEY, symbol VARCHAR(10),	name VARCHAR(100),	current_price DECIMAL(18, 6),	market_cap BIGINT,	market_cap_rank INT,	total_volume BIGINT,	circulating_supply DECIMAL(20, 6),	total_supply DECIMAL(20, 6),	ath DECIMAL(18, 6),	atl DECIMAL(18, 6),	date DATE",
    "Crypto_prices": "coin_id	VARCHAR(50), date	DATE, prices_usd DECIMAL(18, 6),FOREIGN KEY (coin_id) REFERENCES Cryptocurrencies(id)",
    "Oil_prices": "Date DATE PRIMARY KEY, Price DECIMAL(18, 6)",
    "Stocks_prices": "Date DATE,	Open DECIMAL(18, 6),	High DECIMAL(18, 6) , Low DECIMAL(18, 6),	Close DECIMAL(18, 6),	Volume DECIMAL(18, 6),	Ticker DECIMAL(18, 6)"
}

for table_name, schema in tables.items():
    cursor.execute(f"CREATE TABLE IF NOT EXISTS {table_name} ({schema})")

In [3]:
# List of pairs
df_list = [
    (crpyto_curr, "Cryptocurrencies"),
    (crpyto_price, "Crypto_prices"),
    (oil_price, "Oil_prices"),
    (stocks_price, "Stocks_prices")
]

for df, table_name in df_list:
    # FIX: Wrap column names in [] to handle colons or spaces
    cols = ", ".join([f"[{col}]" for col in df.columns])
    placeholders = ", ".join(["?"] * len(df.columns))

    # FIX: Wrap table name in [] just in case
    sql = f"INSERT OR REPLACE INTO [{table_name}] ({cols}) VALUES ({placeholders})"

    for _, row in df.iterrows():
        # Ensure values are passed as a clean tuple
        cursor.execute(sql, tuple(row))

conn.commit()

print("Data inserted successfully without token errors.")

Data inserted successfully without token errors.

# STREAMLIT

In [8]:
!pip install datetime timedelta

Collecting datetime
  Downloading datetime-6.0-py3-none-any.whl.metadata (34 kB)
Collecting timedelta
  Downloading timedelta-2020.12.3.tar.gz (1.6 kB)
  Preparing metadata (setup.py) ... done
Collecting zope.interface (from datetime)
  Downloading zope_interface-8.2-cp312-cp312-manylinux1_x86_64.manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_5_x86_64.whl.metadata (45 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.4/45.4 kB 3.3 MB/s eta 0:00:00
Requirement already satisfied: pytz in /usr/local/lib/python3.12/dist-packages (from datetime) (2025.2)
Downloading datetime-6.0-py3-none-any.whl (52 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.6/52.6 kB 3.6 MB/s eta 0:00:00
Downloading zope_interface-8.2-cp312-cp312-manylinux1_x86_64.manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_5_x86_64.whl (264 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 264.9/264.9 kB 10.4 MB/s eta 0:00:00
Building wheels for collected packages: timedelta
  Building wheel for timedelta (setup.py) ... done
  Created wheel for timedelta: filename=timedelta-2020.12.3-py3-none-any.whl size=1555 sha256=d66fac73d0ff0a5c24dec685b1e21b0e8206b3f57a7014fd7eb6ed04a691ad94
  Stored in directory: /root/.cache/pip/wheels/8d/fb/00/1ed61af72177d4c71909dc4ad90d4ce863e0aaed78e31206e0
Successfully built timedelta
Installing collected packages: timedelta, zope.interface, datetime
Successfully installed datetime-6.0 timedelta-2020.12.3 zope.interface-8.2

In [9]:
!pip install streamlit streamlit_option_menu

Collecting streamlit
  Downloading streamlit-1.55.0-py3-none-any.whl.metadata (9.8 kB)
Collecting streamlit_option_menu
  Downloading streamlit_option_menu-0.4.0-py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<8,>=5.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.2.6)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (8.3.1)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /usr/local/lib/python3.12/dist-packages (from streamlit) (3.1.46)
Requirement already satisfied: numpy<3,>=1.23 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.0.2)
Requirement already satisfied: packaging>=20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (26.0)
Requirement already satisfied: pandas<3,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.2.2)
Requirement already satisfied: pillow<13,>=7.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (11.3.0)
Collecting pydeck<1,>=0.8.0b4 (from streamlit)
  Downloading pydeck-0.9.1-py2.py3-none-any.whl.metadata (4.1 kB)
Requirement already satisfied: protobuf<7,>=3.20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.29.6)
Requirement already satisfied: pyarrow>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (18.1.0)
Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.32.4)
Requirement already satisfied: tenacity<10,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (9.1.4)
Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.10.2)
Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.5.1)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (4.15.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.0.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (4.26.0)
Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2.18.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=1.4.0->streamlit) (2025.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2026.2.25)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.3)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.30.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas<3,>=1.4.0->streamlit) (1.17.0)
Downloading streamlit-1.55.0-py3-none-any.whl (9.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.1/9.1 MB 58.5 MB/s eta 0:00:00
Downloading streamlit_option_menu-0.4.0-py3-none-any.whl (829 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 829.3/829.3 kB 43.3 MB/s eta 0:00:00
Downloading pydeck-0.9.1-py2.py3-none-any.whl (6.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.9/6.9 MB 89.7 MB/s eta 0:00:00
Installing collected packages: pydeck, streamlit, streamlit_option_menu
Successfully installed pydeck-0.9.1 streamlit-1.55.0 streamlit_option_menu-0.4.0

In [10]:
!pip install -q streamlit
!wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
!chmod +x cloudflared-linux-amd64
import subprocess
subprocess.Popen(["./cloudflared-linux-amd64", "tunnel", "--url", "http://localhost:8501"])
!nohup /content/cloudflared-linux-amd64 tunnel --url http://localhost:8501 &

--2026-03-22 18:48:02--  https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
Resolving github.com (github.com)... 140.82.112.3
Connecting to github.com (github.com)|140.82.112.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://github.com/cloudflare/cloudflared/releases/download/2026.3.0/cloudflared-linux-amd64 [following]
--2026-03-22 18:48:02--  https://github.com/cloudflare/cloudflared/releases/download/2026.3.0/cloudflared-linux-amd64
Reusing existing connection to github.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://release-assets.githubusercontent.com/github-production-release-asset/106867604/731ab2f8-6b77-4adb-a7b3-1104525e9d72?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-03-22T19%3A27%3A45Z&rscd=attachment%3B+filename%3Dcloudflared-linux-amd64&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-03-22T18%3A27%3A06Z&ske=2026-03-22T19%3A27%3A45Z&sks=b&skv=2018-11-09&sig=Tq3zusFEV5bOu4ht4LCkgVnR%2FLiJyB%2FoOrw7pKJg3r0%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3NDIwNzA4MiwibmJmIjoxNzc0MjA1MjgyLCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.z2pGglwzeYyngzNYrz-AuN0_o2yMc_J9qySTDRYMIGw&response-content-disposition=attachment%3B%20filename%3Dcloudflared-linux-amd64&response-content-type=application%2Foctet-stream [following]
--2026-03-22 18:48:02--  https://release-assets.githubusercontent.com/github-production-release-asset/106867604/731ab2f8-6b77-4adb-a7b3-1104525e9d72?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-03-22T19%3A27%3A45Z&rscd=attachment%3B+filename%3Dcloudflared-linux-amd64&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-03-22T18%3A27%3A06Z&ske=2026-03-22T19%3A27%3A45Z&sks=b&skv=2018-11-09&sig=Tq3zusFEV5bOu4ht4LCkgVnR%2FLiJyB%2FoOrw7pKJg3r0%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3NDIwNzA4MiwibmJmIjoxNzc0MjA1MjgyLCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.z2pGglwzeYyngzNYrz-AuN0_o2yMc_J9qySTDRYMIGw&response-content-disposition=attachment%3B%20filename%3Dcloudflared-linux-amd64&response-content-type=application%2Foctet-stream
Resolving release-assets.githubusercontent.com (release-assets.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to release-assets.githubusercontent.com (release-assets.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 39667364 (38M) [application/octet-stream]
Saving to: ‘cloudflared-linux-amd64’

cloudflared-linux-a 100%[===================>]  37.83M   140MB/s    in 0.3s

2026-03-22 18:48:03 (140 MB/s) - ‘cloudflared-linux-amd64’ saved [39667364/39667364]

nohup: appending output to 'nohup.out'

In [16]:
%%writefile cross.py

import streamlit as st
from streamlit_option_menu import option_menu
import sqlite3
import pandas as pd
import time
from datetime import date

# ---------------------- CONFIG ----------------------
st.set_page_config(
    page_title="Cross-Market Analysis",
    page_icon="📊",
    layout="wide"
)

# ---------------------- DB CONNECTION ----------------------
conn = sqlite3.connect("Cross_Market_Analysis")
cursor = conn.cursor()

# ---------------------- SIDEBAR ----------------------
with st.sidebar:
    page = option_menu(
        menu_title="🌐 Navigation",
        options=["📊 Market Overview", "🔎 SQL Query Runner", "🏆 Top 3 Crypto Analysis"],
        icons=[" ", " ", " "],
        menu_icon =" ",
        default_index=0,
    )

# ======================================================
# PAGE 1 : FILTERS & DATA EXPLORATION
# ======================================================
if page == "📊 Market Overview":

    st.title("📊 Cross-Market Overview")
    st.caption("Crypto • Oil • Stock Market | SQL-powered analytics")

    # ---------- DATE FILTER ----------
    col1, col2 = st.columns(2)

    min_date = date(2020, 1, 1)
    max_date = date(2026, 3, 3)

    with col1:
      start_date = st.date_input("Start Date",value=min_date,min_value=min_date,max_value=max_date,key="c1")
    with col2:
      end_date = st.date_input("End Date", value=max_date,min_value=min_date,max_value=max_date,key="c2")

    # ---------- KPI CARDS ----------
    k1, k2, k3, k4 , k5 = st.columns(5)

    btc_avg = pd.read_sql(f"""
        SELECT AVG(prices_usd)
        FROM Crypto_prices
        WHERE coin_id='bitcoin' and
        date BETWEEN ? AND ?
        """, conn,params=(start_date, end_date)).iloc[0,0]

    oil_avg = pd.read_sql(f"""
        SELECT AVG(price)
        FROM Oil_prices
        WHERE date BETWEEN '{start_date}' AND '{end_date}'
    """, conn).iloc[0, 0]

    sp500_avg = pd.read_sql(f"""
        SELECT AVG(close)
        FROM Stocks_prices
        WHERE ticker='^GSPC'
        AND date BETWEEN '{start_date}' AND '{end_date}'
    """, conn).iloc[0, 0]

    nifty_avg = pd.read_sql(f"""
        SELECT AVG(close)
        FROM Stocks_prices
        WHERE ticker='^NSEI'
        AND date BETWEEN '{start_date}' AND '{end_date}'
    """, conn).iloc[0, 0]

    nasdaq_avg = pd.read_sql(f"""
        SELECT AVG(close)
        FROM Stocks_prices
        WHERE ticker='^IXIC'
        AND date BETWEEN '{start_date}' AND '{end_date}'
    """, conn).iloc[0, 0]

    k1.metric("₿ Bitcoin Avg ($)", f"{btc_avg:,.2f}")
    k2.metric("🛢️ Oil Avg ($)", f"{oil_avg:,.2f}" if oil_avg else "N/A")
    k3.metric("📈 S&P 500 Avg", f"{sp500_avg:,.2f}" if sp500_avg else "N/A")
    k4.metric("🇮🇳 NIFTY Avg", f"{nifty_avg:,.2f}" if nifty_avg else "N/A")
    k5.metric("🐂 NASDAQ Avg", f"{nasdaq_avg:,.2f}" if nasdaq_avg else "N/A")

    st.divider()

    # ---------- FILTERED DATA TABLE ----------
    st.subheader("📈 Market Pulse")

    snapshot_df = pd.read_sql(f"""
        SELECT cp.date,
               cp.prices_usd AS bitcoin_price,
               op.price AS oil_price,
               sp1.close AS sp500,
               sp2.close AS nifty,
               sp3.close AS nasdaq
        FROM Crypto_prices cp
        JOIN Oil_prices op ON cp.date = op.date
        JOIN Stocks_prices sp1 ON cp.date = sp1.date AND sp1.ticker='^GSPC'
        JOIN Stocks_prices sp2 ON cp.date = sp2.date AND sp2.ticker='^NSEI'
        JOIN Stocks_prices sp3 ON cp.date = sp3.date AND sp3.ticker='^IXIC'
        WHERE cp.coin_id='bitcoin'
        AND cp.date BETWEEN '{start_date}' AND '{end_date}'
        ORDER BY cp.date DESC
    """, conn)

    st.dataframe(snapshot_df, use_container_width=True)

# ======================================================
# PAGE 2 : SQL QUERY RUNNER
# ======================================================
elif page == "🔎 SQL Query Runner":

    st.title("🔎 SQL Query Runner")

    st.caption("Predefined analytical SQL queries")

    queries = {

# ===============================
#  CRYPTOCURRENCIES (5)
# ===============================

"Top 3 Cryptocurrencies by Market Cap": """
    SELECT name, market_cap
    FROM Cryptocurrencies
    ORDER BY market_cap DESC
    LIMIT 3;
""",

"Coins with Circulating Supply > 90%": """
    SELECT name , circulating_supply , total_supply
    FROM Cryptocurrencies
    WHERE circulating_supply / total_supply > 0.9;
""",

"Coins Near All-Time High (Within 10%)": """
    SELECT name, current_price, ath
    FROM Cryptocurrencies
    WHERE current_price >= ath * 0.9;
""",

"Average Market Cap Rank (Volume > $1B)": """
    SELECT name, AVG(market_cap_rank)  AS avg_rank
    FROM Cryptocurrencies
    WHERE total_volume > 1000000000;
""",

"Most Recently Updated Coin": """
    SELECT name, date
    FROM Cryptocurrencies
    ORDER BY date DESC
    LIMIT 1;
""",

# ===============================
#  CRYPTO PRICES (5)
# ===============================

"Highest Bitcoin Price (Last 1 year)": """
    SELECT MAX(prices_usd), date
    FROM Crypto_prices
    WHERE coin_id = 'bitcoin';
""",

"Average Ethereum Price (Past 1 Year)": """
    SELECT coin_id, AVG(prices_usd)
    FROM Crypto_prices
    WHERE coin_id = 'ethereum';
""",

"Bitcoin Prices – January 2026": """
    SELECT coin_id, date, prices_usd
    FROM Crypto_prices
    WHERE coin_id = 'bitcoin'
    AND date BETWEEN '2026-01-01' AND '2026-01-31';
""",

"Coin with Highest Average Price": """
    SELECT coin_id, AVG(prices_usd) AS avg_price
    FROM Crypto_prices
    GROUP BY coin_id
    ORDER BY avg_price DESC
    LIMIT 1;
""",

"Bitcoin % Change (Mar 2025 – Mar 2026)": """
    SELECT coin_id,
    ((MAX(prices_usd) - MIN(prices_usd)) / MIN(prices_usd)) * 100 AS pct_change
    FROM Crypto_prices
    WHERE coin_id='bitcoin'
    AND date BETWEEN '2025-03-03' AND '2026-03-03';
""",

# ===============================
#  OIL PRICES (5)
# ===============================

"Highest Oil Price (Last 5 Years)": """
    SELECT MAX(price) AS Price_USD, date
    FROM Oil_prices
    WHERE date >= DATE('2026-03-03', '-5 years');
""",

"Average Oil Price Per Year": """
    SELECT strftime('%Y', date) AS year, AVG(price) AS Avg_price_USD
    FROM Oil_prices
    GROUP BY year;
""",

"Oil Prices During COVID Crash": """
    SELECT *
    FROM Oil_prices
    WHERE date BETWEEN '2020-03-01' AND '2020-04-30';
""",

"Lowest Oil Price (Last 5 Years)": """
    SELECT MIN(price) , date
    FROM Oil_prices
    WHERE date >= DATE('2026-03-03', '-5 years');
""",

"Yearly Oil Price Volatility": """
    SELECT strftime('%Y', date) AS Year,
           MAX(price) - MIN(price) AS Volatility,MAX(price), MIN(price)
    FROM Oil_prices
    GROUP BY Year;
""",

# ===============================
#  STOCK PRICES (5)
# ===============================

"All Prices for NSEI S&P 500": """
    SELECT *
    FROM Stocks_prices
    WHERE ticker = '^NSEI';
""",

"Highest NASDAQ (^IXIC) Closing Price": """
    SELECT MAX(close) , ticker , Date
    FROM Stocks_prices
    WHERE ticker='^IXIC';
""",

"Top 5 Volatile S&P 500 Days(^GSPC)": """
    SELECT date, high , low, (high - low) AS volatility
    FROM Stocks_prices
    WHERE ticker='^GSPC'
    ORDER BY volatility DESC
    LIMIT 5;
""",

"Monthly Average Closing Price (All Tickers)": """
    SELECT ticker,
           strftime('%Y-%m', date) AS Month,
           AVG(close) AS Avg_close
    FROM Stocks_prices
    GROUP BY ticker, month;
""",

"Average NSEI Volume (2024)": """
    SELECT ticker, AVG(volume)
    FROM Stocks_prices
    WHERE ticker='^NSEI'
    AND date BETWEEN '2024-01-01' AND '2024-12-31';
""",

# ===============================
#  JOINS QUERIES (10)
# ===============================

"Bitcoin vs Oil Average Price (2025)": """
    SELECT AVG(cp.prices_usd) AS Btc_avg,
           AVG(op.price) AS Oil_avg
    FROM Crypto_prices cp
    JOIN Oil_prices op ON cp.date = op.date
    WHERE cp.coin_id='bitcoin'
    AND cp.date BETWEEN '2025-01-01' AND '2025-12-31';
""",

"Bitcoin vs S&P 500 (Daily)": """
    SELECT cp.date, cp.prices_usd AS Btc_price, sp.close AS sp500
    FROM Crypto_prices cp
    JOIN Stocks_prices sp ON cp.date = sp.date
    WHERE cp.coin_id='bitcoin'
    AND sp.ticker='^GSPC';
""",

"Ethereum vs NASDAQ (2025)": """
    SELECT cp.date, cp.prices_usd, sp.close
    FROM Crypto_prices cp
    JOIN Stocks_prices sp ON cp.date = sp.date
    WHERE cp.coin_id='ethereum'
    AND sp.ticker='^IXIC'
    AND cp.date BETWEEN '2025-01-01' AND '2025-12-31';
""",

"Oil Spike Days vs Bitcoin Price": """
    SELECT op.date, op.price AS Oil_price, cp.prices_usd AS Btc_price
    FROM Oil_prices op
    JOIN Crypto_prices cp ON op.date = cp.date
    WHERE cp.coin_id='bitcoin'
    AND op.price > (SELECT AVG(price) FROM Oil_prices)
    ORDER BY op.date DESC;
""",

"Top 3 Coins vs NIFTY (^NSEI)": """
    SELECT cp.date, cp.coin_id, cp.prices_usd, sp.close AS NIFTY
    FROM Crypto_prices cp
    JOIN Stocks_prices sp ON cp.date = sp.date
    WHERE sp.ticker='^NSEI';
""",

"S&P 500 (^GSPC) vs Oil Prices on same date": """
    SELECT sp.date, sp.close, op.price AS Oil_Price
    FROM Stocks_prices sp
    JOIN Oil_prices op ON sp.date = op.date
    WHERE sp.ticker='^GSPC';
""",

"Bitcoin vs Oil Correlation Dataset": """
    SELECT cp.date, cp.prices_usd AS Btc_price, op.price AS Oil_Price
    FROM Crypto_prices cp
    JOIN Oil_prices op ON cp.date = op.date
    WHERE cp.coin_id='bitcoin'
    ORDER BY cp.date DESC;
""",

"NASDAQ vs Ethereum Trend": """
    SELECT cp.date, cp.prices_usd, sp.close
    FROM Crypto_prices cp
    JOIN Stocks_prices sp ON cp.date = sp.date
    WHERE cp.coin_id='ethereum'
    AND sp.ticker='^IXIC'
    ORDER BY cp.date DESC;
""",

"Top 3 Cryptos vs Stock Indices (2025)": """
    SELECT cp.date, cp.coin_id, cp.prices_usd, sp.ticker, sp.close
    FROM Crypto_prices cp
    JOIN Stocks_prices sp ON cp.date = sp.date
    WHERE cp.date BETWEEN '2025-01-01' AND '2025-12-31';
""",

"Bitcoin + Oil + NIFTY(^NSEI) Daily Comparison": """
    SELECT cp.date,
           cp.prices_usd AS Btc_price,
           op.price AS Oil_price,
           sp.close AS NIFTY
    FROM Crypto_prices cp
    JOIN Oil_prices op ON cp.date = op.date
    JOIN Stocks_prices sp ON cp.date = sp.date
    WHERE cp.coin_id='bitcoin'
    AND sp.ticker='^NSEI';
""",
# ======================================================
# My analysis
# ======================================================

"Bitcoin & Oil Daily Trend Tracker": """
SELECT
    cp.date,
    cp.prices_usd AS Btc_price,
    op.price AS Oil_price,
    -- Label movements
    CASE WHEN cp.prices_usd > LAG(cp.prices_usd) OVER (ORDER BY cp.date) THEN '🔼' ELSE '🔻' END AS Btc_move,
    CASE WHEN op.price > LAG(op.price) OVER (ORDER BY op.date) THEN '🔼' ELSE '🔻' END AS Oil_move
FROM Crypto_prices cp
JOIN Oil_prices op ON cp.date = op.date
WHERE cp.coin_id = 'bitcoin'
ORDER BY cp.date DESC;
""",


"Bitcoin & NASDAQ Daily Trend Tracker": """
SELECT
    cp.date,
    cp.prices_usd AS Btc_price,
    sp.close AS NASDAQ_price,
    -- Label movements
    CASE WHEN cp.prices_usd > LAG(cp.prices_usd) OVER (ORDER BY cp.date) THEN '🔼' ELSE '🔻' END AS Btc_move,
    CASE WHEN sp.close > LAG(sp.close) OVER (ORDER BY sp.date) THEN '🔼' ELSE '🔻' END AS Stock_move
FROM Crypto_prices cp
JOIN Stocks_prices sp ON cp.date = sp.date
WHERE cp.coin_id = 'bitcoin' AND sp.ticker='^IXIC'
ORDER BY cp.date DESC;
""",


"Bitcoin & S&P 500 Daily Trend Tracker": """
SELECT
    cp.date,
    cp.prices_usd AS Btc_price,
    sp.close AS SP500_price,
    -- Label movements
    CASE WHEN cp.prices_usd > LAG(cp.prices_usd) OVER (ORDER BY cp.date) THEN '🔼' ELSE '🔻' END AS Btc_move,
    CASE WHEN sp.close > LAG(sp.close) OVER (ORDER BY sp.date) THEN '🔼' ELSE '🔻' END AS Stock_move
FROM Crypto_prices cp
JOIN Stocks_prices sp ON cp.date = sp.date
WHERE cp.coin_id = 'bitcoin' AND sp.ticker='^GSPC'
ORDER BY cp.date DESC;
""",

"Bitcoin & NIFTY Daily Trend Tracker": """
SELECT
    cp.date,
    cp.prices_usd AS Btc_price,
    sp.close AS NIFTY_price,
    -- Label movements
    CASE WHEN cp.prices_usd > LAG(cp.prices_usd) OVER (ORDER BY cp.date) THEN '🔼' ELSE '🔻' END AS Btc_move,
    CASE WHEN sp.close > LAG(sp.close) OVER (ORDER BY sp.date) THEN '🔼' ELSE '🔻' END AS Stock_move
FROM Crypto_prices cp
JOIN Stocks_prices sp ON cp.date = sp.date
WHERE cp.coin_id = 'bitcoin' AND sp.ticker='^NSEI'
ORDER BY cp.date DESC;
"""
}


    selected_query = st.selectbox("📌 Select a Query", list(queries.keys()))

    if st.button("▶ Run Query"):
        result = pd.read_sql(queries[selected_query], conn)
        with st.spinner("⚡ Running Instant Analysis..."):
          time.sleep(2)
          st.success("Query executed successfully")
        st.dataframe(result, use_container_width=True)

    st.caption("🔗 Direct-to-source: Executing against the SQL database.")

# ======================================================
# PAGE 3 : TOP 3 CRYPTO ANALYSIS (as per document)
# ======================================================
elif page == "🏆 Top 3 Crypto Analysis":

    st.title("🏆 Top 3 Crypto Analysis")
    st.caption("Daily price analysis for top cryptocurrencies")

    coins = pd.read_sql("""
        SELECT DISTINCT coin_id
        FROM Crypto_prices
    """, conn)['coin_id'].tolist()

    selected_coin = st.selectbox("Select a Cryptocurrency", coins)

    # ---------- DATE FILTER ----------

    col1, col2 = st.columns(2)

    min_date = date(2025, 3, 3)
    max_date = date(2026, 3, 3)

    with col1:
      start_date = st.date_input("Start Date",value=min_date,min_value=min_date,max_value=max_date,key="c1")
    with col2:
      end_date = st.date_input("End Date", value=max_date,min_value=min_date,max_value=max_date,key="c2")

    # ---------- FILTERED DATA TABLE ----------

    price_df = pd.read_sql(f"""
        SELECT date, prices_usd
        FROM Crypto_prices
        WHERE coin_id='{selected_coin}'
        AND date BETWEEN '{start_date}' AND '{end_date}'
        ORDER BY date
    """, conn)

    podium_map = {
    "bitcoin": "🥇 1st Place: BITCOIN",
    "ethereum": "🥈 2nd Place: ETHEREUM",
    "tether": "🥉 3rd Place: TETHER"}

    display_title = podium_map[selected_coin.lower()]
    st.subheader(display_title)

    # ---------- FILTERED DATA GRAPH ----------
    st.line_chart(price_df.set_index('date'))

    # ---------- FILTERED DATA FRAME ----------

    st.dataframe(price_df, use_container_width=True)

Overwriting cross.py

In [12]:
!streamlit run /content/cross.py &>/content/logs.txt &

In [13]:
!grep -o 'https://.*\.trycloudflare.com' nohup.out | head -n 1 | xargs -I {} echo "Your tunnel url {}"

Your tunnel url https://kitty-drag-metals-relax.trycloudflare.com